apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::750246434075:role/eksctl-eksctl-demo-nodegroup-ng-5-NodeInstanceRole-O6YN343GZ983
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-27T15:42:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1664"
  uid: f2ab5a73-54dc-4360-a9cf-a5db5cf0cd39
